name: metagoflow
channels:
  - bioconda
  - defaults
dependencies:
  - python=3.8
  - nodejs
  - pip:
      - cwltool==3.1.20230624081518
      - cwlref-runner
      - rocrate==0.8.0
      - ruamel-yaml==0.17.32
